name: CI

on:
  push:
    branches:
      - '2.x'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        doc-type: ['HTML', 'EPUB', 'PDF']

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        fetch-depth: 1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install packages
      run: |
        sudo apt install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-lang-all

    - name: Build Docs
      run: |
        if [[ ${{ matrix.doc-type }} == 'HTML' ]]; then make html; fi
        if [[ ${{ matrix.doc-type }} == 'EPUB' ]]; then make epub; fi
        if [[ ${{ matrix.doc-type }} == 'PDF' ]]; then make latex; fi
